//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LicenseKey
{
    public long Id { get; set; }
    public string KeyCode { get; set; }
    public string MachineCode { get; set; }
    public System.DateTime CreatedOn { get; set; }
    public bool IsExhausted { get; set; }
    public string ProductUID { get; set; }
    public Nullable<long> PaymentCodeId { get; set; }
    public string FirstName { get; set; }
    public string Lastname { get; set; }
    public string Email { get; set; }

    public virtual PaymentCode PaymentCode { get; set; }
}

public partial class PaymentCode
{
    public PaymentCode()
    {
        this.LicenseKeys = new HashSet<LicenseKey>();
    }

    public long Id { get; set; }
    public string Code { get; set; }
    public bool IsExhausted { get; set; }
    public int ValidityDays { get; set; }
    public string AppVersion { get; set; }

    public virtual ICollection<LicenseKey> LicenseKeys { get; set; }
}
